import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import ReturnToTop from "@/components/return-to-top";
import Maintenance from "@/components/sections/maintenance";

const manrope = Manrope({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased relative`}>
        <ReturnToTop />
        <Maintenance />
        {/* {children} */}
      </body>
    </html>
  );
}
